### ISSUE TITLE
[BE] User 엔티티 클래스에서 Car 와 One-To-One 매핑 처리 문제

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#135]
## 설명
현재 ERD 상에서 user : car = 1 : 1 매핑이고, 차량 삭제는 soft delete로 구현하고 있습니다. 이 경우 물리적으로는 user : car = 1 : N 이 되고, 논리적으로 user : car (is_deleted = false) = 1 : 1 이 됩니다. 데이터 베이스 상에서 외래키 제약 조건만 있다면 문제가 없으나 JPA를 사용하는 과정에서 문제가 발생하고 있습니다.

현재 User 엔티티와 Car 엔티티 클래스 코드는 다음과 같습니다.
```java
public class User extends BaseTime {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne(mappedBy = "owner", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Car car;
    // ...
}

```

```java
public class Car extends BaseTime {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;
    //...
}

```

저희는 현재 데이터베이스를 아래 처럼 JPA 를 이용해서 생성하고 있습니다. 그리고 위와 같이 OneToOne 어노테이션을 사용하면 데이터베이스 상에서 Car 테이블의 owner_id 컬럼에 Unique 제약조건이 추가되게 됩니다. 따라서 물리적으로도 1:1 매핑이 강제되기 떄문에 유저가 삭제한 차량이 데이터베이스에 남아있는 경우에 해당 데이터를 삭제하지 않고서는 새로운 차량을 등록할 수 없게 되어 저희의 의도와 어긋나게 동작합니다.
```
  jpa:
    hibernate:
      ddl-auto: update
```

## 해결 방법
저희는 논리적으로는 user : car (isDeleted = false) = 1 : 1 이지만 물리적으로는 user : car = 1 : N 매핑을 유지하고자 하고, JPA 를 사용해서 데이터베이스 테이블을 생성할 것이므로 현재 User, Car에 양방향으로 매핑되어 있는 OneToOne 어노테이션을 삭제하고 Car에만 ManyToOne 어노테이션을 통해 매핑을 생성해야 합니다.

수정된 코드는 아래와 같습니다.
```java
public class User extends BaseTime {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // 아래 필드 삭제
    // @OneToOne(mappedBy = "owner", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    // private Car car;
    // ...
}
```

```java
public class Car extends BaseTime {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne // OneToOne -> ManyToOne으로 수정
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;
}
```
## 변경사항
그리고 위와 같이 로직을 수정했을 때 Service 로직에서 수정해야 할 부분은

1. UserRepository 메서드를 이용해 바로 차량 정보를 가져올 수 없습니다. 따라서 user_id로 차량 정보를 검색하려면 CarRepository에서 owner_id로 검색해야 합니다. 이때, 유저가 현재 등록한 유효한 차량 정보를 가져오려면 isDeleted = false 조건을 추가해야 합니다.
2. 유저가 현재 차량을 갖고 있는지 여부를 판단하는 로직이 의도대로 작동하고 있는지 확인해야 합니다. `select * from car where owner_id = {user_id} and is_deleted = false` 처럼 is_deleted = false인 차량이 있으면 현재 유저가 차량을 이미 등록했다고 볼 수 있을 것 같습니다.

이외에 혹시 제안하고 싶은 방법이 있다면 알려주세요! 자신의 코드에서 변경해야 할 부분이 있는 분들 모두가 동의하시면 위의 방식으로 코드를 수정해서 PR 작성하도록 하겠습니다. :)

에러를 발견해주신 @jomulagy 님과 @thecloer 님께 감사인사 드립니다 ㅎㅎ

**Comment by thecloer** [comment]
현재 구조, 문제 -> 해결 방안, 변경된 구조 -> 사용하는 부분에서 변경해야할 곳
정리를 참 잘하시는군요!

**Comment by kelly1422** [comment]
소프트 딜리트로 구현하다보니 이런 문제가 발생할 수 있네요.
저 방법 좋은 것 같아요, 유저 회원탈퇴 시에 등록한 차량도 삭제하는 부분을 저런 로직으로 수정하도록 하겠습니다!
(사실 상 논리적으로는 User와 Car가 1:1 인데, 물리적으로는 1:M 으로 잘 맞지 않아서 소프트 딜리트용 deleted_car와 같은 테이블을 분리하는 것도... 하나의 방법이 될 수 있겠다는 생각이 듭니다!.)

**Comment by Yoon-Suji** [comment]
@kelly1422 
네 저도 지금까지 1:1 매핑을 소프트 딜리트 형식으로 구현했던 경험이 없어서 이런 케이스에 대해 생각을 못해봤던 것 같아요! 영경님 말씀처럼 테이블을 분리하면 논리적&물리적으로 똑같이 구현하게 되면 더 명확해지니 이해하기 편하겠네요 :)

**Comment by jomulagy** [comment]
고생하셨습니다 수정사항 반영하겠습니다
