### ISSUE TITLE
[BE] 세부 모델명 조회 API 쿼리 성능 개선 (N+1 문제 해결)

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#146]
GET /categories API의 쿼리 로깅을 확인하며 흥미로운 지점을 발견해서 공유합니다!

## 문제상황
현재 해당 요청의 서비스 로직은 다음과 같습니다.

```java
public List<GetCategoriesResponseDto.CategoryDto> getSubcategories() {
    return categoryRepository.findAll().stream()
            .map(GetCategoriesResponseDto.CategoryDto::new)
            .toList();
}
```

그리고 Category 엔티티와 Subcategory 엔티티의 코드는 다음과 같이 현재 OneToMany, ManyToOne 양방향 매핑되어있습니다.
```java
public class Category extends BaseTime {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name", nullable = false)
    private String name;

    @OneToMany(mappedBy = "category")
    private List<Subcategory> subcategories;
}
```

```java
public class Subcategory extends BaseTime {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name", nullable = false, unique = true)
    private String name;

    @ManyToOne()
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;
}
```
현재 우리가 사용하고 있는 Hibernate 버전은 `6.4.1.Final` 이고 OneToMany 어노테이션의 이폴트 FetchType은 FetchType.LAZY 입니다.
```java
// Hibernate 버전 출력 코드
System.out.println(org.hibernate.Version.getVersionString());
```
따라서 서비스 로직에서 categoryRepository.findAll() 메서드를 실행했을 때는 category에 대한 셀렉트 문만 실행이 되고, 그 내부에서 응답 형식에 맞는 DTO를 만들기 위해 category.getSubcategories()를 호출할 때마다 subcategory를 조회하는 셀렉트 문이 실행됩니다. 

```
// 처음 실행되는 하나의 쿼리
Hibernate: select c1_0.id,c1_0.created_at,c1_0.name,c1_0.updated_at from category c1_0

// 이후 getSubcategory() 에 접근할 때마다 실행되는 쿼리: Category 데이터 갯수만큼 실행됨
Hibernate: select s1_0.category_id,s1_0.id,s1_0.created_at,s1_0.name,s1_0.updated_at from subcategory s1_0 where s1_0.category_id=?
```

보통 현업에서는 FetchType.EAGER 를 사용하게 되면 의도치 않은 셀렉트 쿼리가 나갈 수 있기 때문에 FetchType.LAZY 를 사용하는 것을 권장합니다. 하지만 위의 경우만 생각해본다면 우리는 Category와 Category에 연결된 모든 Subcategory 값을 읽어와서 응답해주어야 하기 때문에 항상 Subcategory 값이 필요합니다.

그래서 지연로딩과 즉시로딩을 사용했을 때 응답 속도 차이를 비교해보았습니다. 그런데, 즉시 로딩을 사용하면 categoryRepository.findAll() 메서드를 실행했을 때 바로 JOIN을 한 SELECT 쿼리가 실행될 거라고 기대했지만 동일하게 N개의 SELECT 쿼리가 나가는 것을 확인했습니다. 그저 쿼리가 호출되는 시점의 차이만 있었습니다.

이 문제는 JPA가 아니라 JPQL에 있었습니다. findAll() 메서드는 JPQL에 의해 동작하고, 내부적으로 1. 모든 카테고리를 조회한 후에 2. 해당 카테고리의 subcategory에 FetchType.EAGER가 걸려있으니 다시 subcategory에 대해 select 쿼리를 날린다는 겁니다. **즉, JPQL을 사용하는 이상 FetchType.LAZY, FetchType.EAGER 모두 N+1 문제가 발생하게 됩니다.** 

## 해결 방법: Fetch Join
JPQL에서 이를 해결하기 위한 방법 중 하나는 바로 Fetch Join을 명시적으로 사용하는 것입니다.
CategoryRepository에 아래와 같은 메서드를 추가하겠습니다.
```java
@Query("select c from Category c left join fetch c.subcategories")
List<Category> findAllFetch();
```
그리고 CategoryService에서 findAll 대신에 위에서 선언한 findAllFetch() 메서드를 사용하여 로그를 찍어보면..
```
Hibernate: select c1_0.id,c1_0.created_at,c1_0.name,s1_0.category_id,s1_0.id,s1_0.created_at,s1_0.name,s1_0.updated_at,c1_0.updated_at from category c1_0 left join subcategory s1_0 on c1_0.id=s1_0.category_id
```
드디어 제가 원하고 기대했던 join 쿼리가 딱 하나! 찍히는 걸 확인할 수 있습니다.

포스트맨을 통해 API 응답 시간을 비교해보았을 때도,
지연 로딩과 직접 로딩은 각각 204ms, 197ms로 큰 차이가 없었지만 (당연합니다. 실행되는 쿼리의 갯수는 결국 동일하기 때문입니다.)
<img width="973" alt="스크린샷 2024-02-17 오후 9 11 06" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/70956926/4cf91e23-0486-493b-9339-258d0dfee413">
<img width="973" alt="스크린샷 2024-02-17 오후 9 11 38" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/70956926/a6e0943d-4808-405f-9fbf-111492241f22">

Fetch Join을 사용한 경우에는 163ms 인 것을 확인할 수 있습니다!
<img width="965" alt="스크린샷 2024-02-17 오후 9 16 49" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/70956926/f65affcf-df2e-4c08-ae2e-74cd678d9b7a">

현재 데이터가 많지 않아 차이가 커보이지 않지만 데이터가 많은 경우에는 유의미한 차이가 될 것입니다.

하지만 위처럼 Fetch Join 방식은 직접 쿼리안에 `fetch`를 넣어야 한다는 단점이 있는데요, 이를 보완하는 방법 중 하나는 EntityGraph 어노테이션을 사용하는 것입니다.
```java
@EntityGraph(attributePaths = {"subcategories"}, type = EntityGraphType.FETCH)
@Query("select c from Category c left join c.subcategories")
List<Category> findAllFetch();
```
위와 같이 작성하면 쿼리문 안에 `fetch`를 넣지 않아도 fetch join을 실행할 수 있으며 더욱 명시적으로 확인할 수 있습니다.

마지막으로 유의할 점은, fetch join이 만능은 아니라는 것입니다. 특히 페이지네이션과 관련된 쿼리의 경우 유의해야할 부분이 있다고 합니다. 

관련해서 이 [블로그](https://velog.io/@jinyoungchoi95/JPA-%EB%AA%A8%EB%93%A0-N1-%EB%B0%9C%EC%83%9D-%EC%BC%80%EC%9D%B4%EC%8A%A4%EA%B3%BC-%ED%95%B4%EA%B2%B0%EC%B1%85)글 참고해보면 좋을 것 같습니다.

**Comment by Yoon-Suji** [comment]
그래서 결론은!
GET /categories API에서 양방향 매핑은 유지하되, API를 조회할 때 CategoryRepository.findAll() 메서드가 아닌 Fetch Join을 사용한 메서드로 변경하여 불필요한 N+1 쿼리 문제를 해결하고 검색 성능을 향상시켜보았습니다 ㅎㅎ

**Comment by SuHyeon00** [comment]
정보 공유 감사합니다! 저희가 예상한 바로는 `FetchType.EAGER`을 사용할 경우 여러 개의 쿼리문이 나가지 않고 join을 통해 연결된 모든 데이터가 한 번에 불러올 것으로 생각했는데 `FetchType.LAZY`와 호출 시점의 차이가 있었군요! 다만 언급해주신 대로 페이지네이션을 적용하는 검색 기능에 대해서는 조심해야겠네요. 페이지네이션 기능을 사용할 경우 fetch join으로 조회했을 때 메모리에 모든 정보를 갖고온 후 애플리케이션 단에서 size의 개수만큼만 갖고오는 방식으로 동작한다면 페이지네이션 기능의 의의가 사라질수도 있겠네요. 자칫하면 OOM (Ouf Of Memory)가 발생할 수 있다니... fetch join을 사용할 부분을 신중히 생각해봐야겠어요!
