### ISSUE TITLE
[FE] 로그인 화면으로 리다이렉트 될 때, 에러 화면 보이는 버그

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#159]
## TODO

- [ ] 헤더의 호스트 버튼, 마이페이지 버튼 클릭 시 로그인 화면으로 리다이렉트 되기 전에 에러 화면이 보이는 버그

## 설명

https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/70956926/240bbc6d-4194-493c-a3e1-801a77520240

**Comment by jomulagy** [comment]
수정했습니다!

**Comment by thecloer** [comment]
이슈 닫겠습니다~
