### ISSUE TITLE
[BE] soft delete 한 데이터가 조회될 수 있는 이슈

### ISSUE THREAD

**Issue by kelly1422** [softeerbootcamp-3rd/Team9-HexaCore#161]
## 설명
저희는 현재 차량과 유저를 soft delete로 구현하고 있습니다. 
따로 삭제된 데이터와 테이블을 구분하지 않고, 테이블에 is_delete 칼럼을 추가하여 삭제된 데이터인지를 구분하고 있는데, 
데이터를 조회할 때 JpaRepository 의 기본적인 CRUD 기능을 사용하게 될 경우 몇몇 문제가 발생할 수 있을 것 같습니다.

### findById
```java
User guestUser = userRepository.findById(guestUserId)
                               .orElseThrow(() -> new GeneralException(ErrorCode.USER_NOT_FOUND));

Car car = carRepository.findById(createReservationRequestDto.getCarId())
                        .orElseThrow(() -> new GeneralException(ErrorCode.CAR_NOT_FOUND));
```
많은 부분에서 기본 findById 를 사용하고 있습니다. 
**‼️하지만 이런 경우, 회원탈퇴한 유저나 삭제된 차량이 조회되고 수정될 가능성이 있을 것 같습니다.‼️**

제가 생각한 문제 상황들을 예시로 들어보자면
#### 삭제된 차량 정보 조회 가능
1. 검색 완료 
2. 결과 중 하나의 차량을 호스트가 삭제
3. 그 차량 상세정보를 게스트가 조회
4. 삭제된 차량인데 상세 정보를 조회할 수 있음

#### 회원 탈퇴한 유저 정보 조회 가능
`/users/{userId}` 로 유저 정보를 조회하고 있는데, 
여기서 findById를 쓰면 회원탈퇴한 사용자의 정보도 조회가 됨

```java
Optional<Car> findByIdAndIsDeletedFalse(Long id);
Optional<User> findByIdAndIsDeletedFalse(Long id);
```
### 결론
그렇기에 기본으로 제공해주는 메소드를 사용하는 모든 부분을 AndIsDeletedFalse 조건을 추가한 메소드를 작성해 바꿔줘야 할 것 같습니다.

**Comment by SuHyeon00** [comment]
좋은 생각인 것 같습니다!!

**Comment by jomulagy** [comment]
차량 조회 로직은 현재 수정되어 있는데 user도 같은 문제가 있을 수 있겠군요 수정하겠습니다

**Comment by kelly1422** [comment]
엇 제가 이미 수정해서 지금 pr 날리도록 하겠습니다!
