### ISSUE TITLE
[FE] 클라이언트 초기 설정

### ISSUE THREAD

**Issue by thecloer** [softeerbootcamp-3rd/Team9-HexaCore#4]
## TODO

- [x] Reactjs + TS
- [x] Tailwindcss
- [x] React Router dom
- [x] 경로 별 더미 페이지 생성

## 설명

vite을 이용한 Reactjs + ts 설정
스타일 라이브러리 tailwindcss 적용
SPA 페이지 전환의 편의를 위해 react router 적용

**Comment by crongro** [comment]
Tailwindcss 단점이 있다고 들어는데 고려중이세요?
