### ISSUE TITLE
[BE] @PathVariable 동작과 @ModelAttribute 동작이 사람마다 다르다???

### ISSUE THREAD

**Issue by SuHyeon00** [softeerbootcamp-3rd/Team9-HexaCore#47]
### @ModelAttribute 동작
- @ModelAttribute를 사용할 경우 응답값으로 들어온 body를 dto로 변환하는 과정에서 해당하는 dto에 기본 생성자와 setter 함수가 없을 경우 아래와 같은 에러 메시지가 뜬다. 
```
Cannot resolve parameter names for constructor public com.hexacore.tayo.car.model.CarUpdateDto(java.lang.Integer,java.lang.String,java.lang.String,java.util.List)"
```
근데 같은 jdk 버전을 사용하는 다른 팀원 (수현, 수지, 석규)이 테스트 했을 때는 해당 오류가 뜨지 않고 성공 코드가 뜨는데 일부 팀원(지훈, 영경)은 위와 같은 에러메시지가 뜬다.

### @PathVariable 동작
- @PathVariable 어노테이션을 사용할 때 이전 자바 버전에서는 변수 명을 지정해주지 않아도 오류가 뜨지 않는데 자바 19버전 이상부터는 변수 명을 지정해주지 않을 경우 아래와 같은 에러 메시지가 뜬다.
```
"Name for argument of type [java.lang.Long] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag."
```

**Comment by jomulagy** [comment]
### 예상되는 원인

1. jdk의 버전 차이
  - jdk의 버전이 17과 19로 상이하다는 점을 발견하였다.
  - jdk의 버전을 jdk-17.0.9로 통일 시켰지만 문제가 해결되지 않았다.
2. java_home의 경로 설정
  - java_home의 경로가 업데이트 되지 않았다는 사실을 발견하였다.
  - 환경변수를 편집했지만 문제가 해결되지 않았다.
3. jdk의 종류 차이
  - project SDK 17과 oracle open jdk17의 차이가 있다는 사실을 발견하였다.
  - azul-17로 변경하였지만 해결되지 않았다.
5. window 와 mac 차이 ..??
  - 다행히도 아니었다

**Comment by jomulagy** [comment]
### 해결방법

- Build를 intelliJ로 하는 방식과 gradle로 하는 방식의 차이가 있다는 것을 발견하였다.
- Build를 gradle로 변경하니 @PathVariable과 @AllArgsConstructor @NoArgsConstructor 가 모두 해결되었다..

### gradle vs intelliJ

스프링 프레임워크에서 @PathVariable을 사용할 때, 기본적으로 메서드 매개변수 이름이 URI 경로 변수의 이름으로 사용됩니다. 즉, 메서드 매개변수의 이름과 URI 경로 변수의 이름이 일치해야 합니다. 따라서 IntelliJ IDEA에서는 메서드 매개변수의 이름을 명시적으로 지정해야 합니다.

그러나 Gradle을 사용하여 프로젝트를 빌드할 때 이러한 제약은 없습니다.  Gradle에서는 컴파일러 옵션을 변경하여 메서드 매개변수의 이름이 클래스 파일에 포함되지 않도록 할 수 있습니다. 따라서 빌드 도구에 따라 메서드 매개변수의 이름이 클래스 파일에 포함될 수도 있고 포함되지 않을 수도 있습니다.
