### ISSUE TITLE
image 삭제/수정 방식

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#48]
## TODO

- [ ] 이미지 수정/삭제시 어떤 방식을 사용하는가

## 설명

1. soft delete 방식
2. 영구 삭제 방식

**Comment by jomulagy** [comment]
### 논의 사항
- user에 대한 user data & user action을 분석하기 위해서 soft delete 방식을 사용한다.
- image의 수정은 기존 image의 삭제 + 새 이미지의 등록으로 볼 수 있기 때문에 soft delete 방식을 사용한다.

**Comment by Yoon-Suji** [comment]
## 02/17 논의사항
* 이미지는 soft delete가 아닌 hard delete 방식을 사용한다. (S3 버킷의 객체까지 삭제)
* 왜? -> 이미지를 소프트 딜리트 하는 이유가 명확하지 않다. 유저가 차량을 삭제한 후 동일한 번호의 차량을 재등록할 때에도 이미지를 새로 받기 때문에 소프트 딜리트 한 이미지를 사용하는 로직이 없다.
