### ISSUE TITLE
차량 이미지를 등록/수정하는 방법

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#51]
### 차량 이미지를 등록/수정하는 방법
- [ ] 차량 이미지의 전송 방식

## 설명

- 생각의 흐름
1. 화면에 차량을 등록한 순서대로 표시 해야 되니까 ImageEntity를 index, url로 구성하자
2. 차량을 등록할때는 전송 받은 images 리스트의 순서대로 index를 넣자
  ex) [file1,file2] -> {"index":0,"url":file1.url}....
3. 수정 할 때는?
     - 파일을 수정하지 않아도 모든 파일을 전송받자 -> index 전송 불필요
       - Dto 예시
         - List<MultiPartFile>
     - 수정한 파일만 전송받자 -> index 전송 필요
       - Dto 예시
         - List<ImageDto>

**Comment by jomulagy** [comment]
### Object를 분리하자!!!

- 사진을 등록할때
```
"imageIndexes" : [0,1,2,3,4],
"imageFiles" : [FILE1, FILE2,FILE3,FILE4,FILE5]
```
- postCarDTO
```
private List<MultipartFile> imageFiles;
private List<Integer> imageIndexes;
```
- 사진을 수정할때
```
"imageIndexes" : [0,2],
"imageFiles" : [FILE6, FILE7]
```
- carUpdateDTO
```
private List<MultipartFile> imageFiles;
private List<Integer> imageIndexes;
```

**Comment by thecloer** [comment]
오프라인으로 대답한 이슈입니다.
혼잣말 아닙니다 오해하지 말아주세요ㅋㅋㅋ
