### ISSUE TITLE
[BE] 예약 동시성 문제

### ISSUE THREAD

**Issue by SuHyeon00** [softeerbootcamp-3rd/Team9-HexaCore#52]
## 설명

스프링은 데이터베이스 연결을 미리 생성하여 `풀(Pool)`에 보관해두고, 요청이 들어올 때마다 (각각의 스레드 마다) 이 연결을 `풀(pool)`에서 가져다 사용하는 방식으로 데이터베이스 연결을 생성합니다.

이러한 풀링 방식을 통해 데이터베이스와 연결을 종료하는 비용을 줄이고 ,연결을 재 사용할 수 있도록 되어있습니다. 따라서, 각각의 스레드가 동시에 데이터베이스에 접근이 가능합니다.

이럴 경우 같은 차량에 대해 겹치는 시간의 예약 요청이 동시에 들어올 경우 동시성 이슈가 발생할 수 있습니다. 이런 동시성 이슈를 어떻게 해결할 수 있을지 논의해봅시다!

**Comment by thecloer** [comment]
두개 이상의 스레드가 동일한 자원에 대해 쓰기 연산을 할 경우 race condition이 발생한다고 저희 모두가 알고 있었지만 이를 두개 이상의 요청과 DB의 특정 레코드로 구체화해서 생각하다 보니 놓쳤던 부분인 것 같네요 🤔

먼저 저희 서비스에서 주로 발생할 수 있는 DB 동시성 문제들에 대해 정리한 후 그 문제점들의 해경 방안들을 나열하고 논의해봐요!

**Comment by SuHyeon00** [comment]
우선, 저희 서비스에서 주로 발생할 수 있는 DB 동시성 문제들을 정리해보았습니다.

**1. 두 명 이상의 사용자가 동일한 차량에 대해서 겹치는 기간의 예약 요청을 하는 상황**

**2. 호스트가 본인 차량의 예약 가능 날짜를 수정하는 동시에 사용자가 해당 날짜를 포함하여 호스트의 차량을 대여하고자 하는 상황**

**3. 호스트가 등록한 차량을 삭제하는 동시에 해당 차량에 대한 게스트의 예약이 들어오는 상황**

추가로 발생할 수 있는 문제상황이 있다면 문제 번호를 **4.** 로 달아서 작성해주세요!

**Comment by Yoon-Suji** [comment]
관련해서 찾아본 내용을 간단하게 정리해봤습니다.

## DB 동시성 문제 제어 방법 3가지
**1. Synchronized**
  * 하나의 서버 내에서 Synchronized 적용된 코드는 한 번에 하나의 스레드만 접근 가능
  
**2. Optimistic Lock 사용**
  * 동시에 여러 트랜잭션이 데이터를 수정할 가능성이 낮다고 "낙관적"으로 가정, 실제 DB에서 Lock을 거는 게 아니라 어플리케이션 레벨에서 관리
  * Version 어노테이션 을 사용해서 구현 -> 엔티티가 데이터베이스에 저장될 때 버전 번호가 함께 저장되며, 데이터를 업데이트할 때 이 버전 번호를 검사
  * 트랜잭션이 데이터를 업데이트할 때, 저장된 버전 번호와 현재 엔티티의 버전 번호를 비교 -> 만약 다른 트랜잭션이 이미 데이터를 업데이트하여 버전 번호가 변경되었다면, 현재 트랜잭션은 OptimisticLockException을 발생시키고 롤백
  
**3. Pessimistic Lock 사용**
* 데이터를 읽거나 수정하기 전에 명시적으로 락을 걸어 다른 트랜잭션이 동시에 접근하지 못하게 함
* Lock 어노테이션과 함께 LockModeType을 지정하여 사용


## 스프링 JPA에서 락 동작 방식
스프링 JPA에서는 EntityManager를 통해 락을 관리합니다. 리포지토리 메서드에 Lock 어노테이션을 사용하여 락 모드를 지정하면, 스프링 데이터 JPA는 해당 락 모드에 따라 데이터베이스에 락을 요청합니다. Transactional 어노테이션과 함께 사용될 때, 락은 트랜잭션의 일부로 처리되어, 트랜잭션이 커밋되거나 롤백될 때 자동으로 해제됩니다.

## MySQL에서의 락 적용
* MySQL(InnoDB 스토리지 엔진)에서는 낙관적 락을 구현할 때 버전 관리 기법을 사용할 수 있으며, 이는 주로 애플리케이션 레벨에서 구현됩니다.
* 비관적 락의 경우, InnoDB는 트랜잭션 격리 수준에 따라 자동으로 로우 레벨의 락을 관리합니다. 스프링 데이터 JPA를 통해 요청된 비관적 락 모드는 SQL 쿼리에 FOR UPDATE (PESSIMISTIC_WRITE), LOCK IN SHARE MODE (PESSIMISTIC_READ) 등의 절을 추가하여 데이터베이스에 전달됩니다.
MySQL에서는 REPEATABLE READ가 기본 격리 수준이지만, 비관적 락을 요청하면 MySQL은 해당 쿼리에 대해 명시적인 락을 수행하여 다른 트랜잭션의 접근을 제어합니다.

## 논의할 부분
* 개인적인 생각으로 저희는 "동시에 같은 데이터에 접근하는 다른 트랜잭션들 사이의 동시성을 제어"해야 하므로 데이터 단위로 Lock을 걸어야 할 것 같습니다. Optimistic Lock을 사용하는 경우에는 락을 거는 오버헤드가 없어 성능이 비교적 좋지만, 충돌이 발생했을 때 롤백과 재시도 로직을 애플리케이션에서 구현해야 하고 충돌이 자주 일어난다면 롤백 오버헤드가 오히려 더 커질 수도 있다는 단점이 있습니다. Pessimistic Lock은 데이터베이스에 큰 부하를 줄 수 있고, 데드락의 위험이 있지만, 충돌 발생 시 롤백 없이 데이터 일관성을 유지할 수 있다고 합니다. 또 Pessimistic Lock에도 종류가 많기 때문에 어떤 Lock을 사용할 지 결정해야 합니다.
* 그래서 저희가 더 고민하고 깊이 공부해서 제대로 구현하려면 Pessimistic Lock을 사용하는 게 좋을 것 같다는 개인적인 의견입니다! 다만 위에서 말했던 것처럼 Pessimistic Lock에도 종류가 많고 데드락이 발생할 시나리오도 찾아서 방지해야 하기 때문에 꽤나 챌린지가 될 것 같습니다..ㅎㅎ

**Comment by thecloer** [comment]
먼저 데이터베이스에서 발생할 수 있는 동시성 문제에 저희 서비스를 대입해서 생각해보면 아래와 같이 생각해 볼 수 있을 것 같아요.

## 데이터베이스 동시성 문제

1. Lost Update Problem
두 트랜잭션이 동시에 같은 데이터를 업데이트 하려 할 때, 한 트랜잭션의 변경이 다른 트랜잭션에 의해 덮어 씌여지는 문제입니다. 이 경우 이전 변경 사항은 손실되고 마지막 변경 사항만 데이터베이스에 반영됩니다.

2. Dirty Read Problem
아직 커밋되지 않은 다른 트랜잭션의 데이터를 읽는 경우에 발생할 수 있는 문제로 이전 트랜잭션이 롤백될 경우 잘못된 데이터를 기반으로 작업할 수 있습니다.

3. Non-Repeatable Read Problem
한 트랜잭션 내에서 같은 쿼리를 두 번 실행 했을 때 다른 결과를 얻는 경우입니다. 두 번의 쿼리 사이에 다른 트랜잭션이 데이터를 수정(업데이트, 삭제)했을 때 생길 수 있는 문제 입니다.

5. Phantom Read Problem
한 트랜잭션 내에서 같은 쿼리를 두 번 실행 했을 때 이전에 없던 데이터가 두 번째 쿼리에 생기는 경우 입니다. 두 번의 쿼리 사이에 다른 트랜잭션이 데이터를 추가했을 때 생길 수 있는 문제입니다.

## 서비스에서 발생할 수 있는 동시성 문제

저희 서비스에서 발생할 수 있는 동시성 문제를 생각해 보면 동시에 같은 자동차에 같은 날짜를 예약할 경우 `Phantom Read`가 일어날 수 있을 것 같아요!

변경된 예약 테이블([issue#79](https://github.com/softeerbootcamp-3rd/Team9-HexaCore/issues/79))에서 동시에 겹치는 날짜에 예약을 생성 할 경우 어떻게 해결할 지 생각해봐요!
![IMG_6551](https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/83699438/2cebb700-91dc-43a9-a4e2-00a045b52520)

**Comment by SuHyeon00** [comment]
![image](https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/90602694/778a0acf-1f0c-4efe-956e-e1f28b3d69ad)

**Comment by thecloer** [comment]
데이터베이스에서 처리하는 것 보다 어플리케이션에서 처리하는 것이 좋을 것 같습니다.
전역 메모리(static ConcurrentHashSet, ConcurrentHashMet 또는 레디스)에 현재 예약 진행 중인 차량과 예약 하려는 날짜를 저장하면 해결 할 수 있을 것 같아요!
예약 요청이 들어오면 예약하려는 자동차와 예약 하려는 날짜로 현재 진행중인 예약이 있는지 전역 메모리에서 확인하고 있다면 예약중이라는 응답을 내려주고 없다면 전역 메모리에 추가하고 예약을 진행한 후 예약이 완료되면 제거해 주는 방법으로 해결하는건 어떨까요?

데이터베이스에 락을 거는 방법으로 해결하는 것보다 어플리케이션에서 해결하는 것이 더 빠르고 저희가 예상하지 못한 문제를 예방할 수 있을 것 같아요

**Comment by Yoon-Suji** [comment]
> 데이터베이스에서 처리하는 것 보다 애플리케이션에서 처리하는 건 어떨까요? 데이터베이스에 락을 거는 방법으로 해결하는 것보다 애플리케이션에서 해결하는 것이 더 빠르고 저희가 예상하지 못한 문제를 예방할 수 있을 것 같아요!
> 
> 전역 저장소(static ConcurrentCollection 또는 레디스)에 현재 예약 진행 중인 차량 id와 예약 하려는 날짜 구간을 저장하면 동시에 같은 차의 겹치는 예약을 할 수 있는 문제를 해결 할 수 있을 것 같아요! 구현 할 때는 전역 저장공간의 인터페이스를 만들고 static ConcurrentCollection으로 구현체를 만들면 이후 레디스나 다른 저장소로 교체하기 쉬울 것 같아요
> 
> 생각한 예약 플로우는 아래와 같이 정리할 수 있을 것 같아요.
> 
> 1. 예약 요청(예약하려는 자동차와 예약하려는 날짜 구간으로 요청)
> 2. 현재 진행 중인 예약 중 같은 자동차이며 예약 구간이 겹치는 예약이 있는 지 전역 저장소에서 확인
>    
>    1. 있다면 다른 사람이 예약 중이라는 메세지 응답
>    2. 없다면 전역 저장소에 저장 후 예약 진행
>       
>       * 예약이 완료 되거나 실패하면 전역 저장소에 저장한 기록 제거

위의 방법 좋은 것 같습니다! 지금까지 데이터베이스 레벨에서 처리하는 방법에 대해서만 고민하고 어플리케이션 레벨에서 처리하는 방법을 생각하지 못했던 것 같네요😱 만약 추후에 서버를 여러 대 띄우게 되는 확장성을 고려했을 때 레디스로 교체하기 쉽게 구현하자는 제안도 좋아보입니다!

**Comment by SuHyeon00** [comment]
저도 위 방법 찬성합니다!! 데이터베이스 레벨에서 처리하기 위해 특정 데이터 row에 lock을 거는 방식으로 테스트해봤더니 데드락이 발생하기도 하더라구요...

예약 플로우(1번 상황)에 대해서는 석규님이 정리해주신 대로 흐름이 흘러가면 동시성 예방이 가능할 것 같은데 다른 2번, 3번 케이스에 대해서도 해당 방식을 적용할 수 있을지 생각해보았습니다.

### 동시성 문제 2 (호스트의 예약 가능 날짜 수정, 게스트의 예약)
1. 호스트가 예약 가능 날짜를 수정하고자 할 경우 전역 저장소에서 carID에 해당하는 상태값 확인 (GUEST_RESERVE)
    1. 있다면 현재 예약 중인 사람이 있다는 메시지 응답
    2. 없다면 전역 저장소에 차량 ID, 상태값 (HOST_EDIT) 저장
2. 예약 요청 시 carID에 해당하는 상태값 확인 (HOST_EDIT, HOST_DELETE)
    1. 상태값이 HOST_EDIT 이라면 호스트가 예약 정보를 수정중이라는 메시지 응답
    2. 상태값이 HOST_DELETE 라면 호스트가 등록한 차량을 삭제중이라는 메시지 응답
    3. 상태값이 없을 경우 1번 예약 플로우로 진행

### 동시성 문제 3 (호스트 차량 삭제, 게스트 예약 요청)
1. 호스트가 등록한 차량을 삭제하고자 할 경우 전역 저장소에서 예약하려는 사람이 있는지 확인
    1. 있다면 현재 예약 중인 사람이 있다는 메시지 응답
    2. 없다면 전역 저장소에 차량 ID, 상태값 (HOST_DELETE) 저장
2. 예약 요청 시 carID에 해당하는 상태값 확인 (HOST_EDIT, HOST_DELETE)
    1. 상태값이 HOST_EDIT 이라면 호스트가 예약 정보를 수정중이라는 메시지 응답
    2. 상태값이 HOST_DELETE 라면 호스트가 등록한 차량을 삭제중이라는 메시지 응답
    3. 상태값이 없을 경우 1번 예약 플로우로 진행

놓친 부분이 있다면 알려주세요!

**Comment by Yoon-Suji** [comment]
@SuHyeon00 케이스별로 정리 감사합니다!

그러면 저희가 사용해야 할 전역 저장소는 GUEST_RESERVE, HOST_EDIT, HOST_DELETE 이렇게 3가지가 되겠네요! 좋은 것 같습니다 :)

**Comment by kelly1422** [comment]
좋은 아이디어입니다💡 애플리케이션 레벨에서 전역으로 thread-safe한 ConcurrentCollection 를 생성하고, 동시성 문제가 일어날 수 있는 데이터 점유 정보를 관리하는 방법 너무 좋습니다! 👍

### 성능 관련 이슈
ConcurrentCollection은 읽기 동작에 잠금을 걸지 않기 위해서 `CopyOnWriteArrayList` 방식으로 write를 한다고 합니다.
이는 리스트를 수정할 때, 배열 전체를 복사하고, 복사한 배열에 수정을 한 뒤, 수정이 완료되면 전체 배열을 갈아끼우는 방식인데, 
공식문서를 보니 비용이 많이 드는 작업이라고 나와있습니다.
[Oracle-CopyOnWriteArrayList](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CopyOnWriteArrayList.html)

저희 서비스 특성상, 전역으로 생성한 ConcurrentCollection를 수정하는 작업이 많이 발생할 것 같습니다. 
각 요청(예약,차량  삭제, 에약 가능 날짜 수정)마다 ConcurrentCollection에 데이터를 추가하고, 끝난 뒤에 ConcurrentCollection에서 데이터를 삭제하는 총 2번이 발생하게 되는게 맞겠죠?
게다가 많은 요청이 동시에 들어오게 된다면 ConcurrentCollection의 크기도 커져 CopyOnWriteArrayList하는 비용이 더 커질텐데..
이런 경우 성능상 이슈가 생길 수 있겠다는 생각이 듭니다.
이 부분에 대해서도 한 번 생각해보면 좋을 것 같아요!

**Comment by thecloer** [comment]
> 좋은 아이디어입니다💡 애플리케이션 레벨에서 전역으로 thread-safe한 ConcurrentCollection 를 생성하고, 동시성 문제가 일어날 수 있는 데이터 점유 정보를 관리하는 방법 너무 좋습니다! 👍
> 
> ### 성능 관련 이슈
> ConcurrentCollection은 읽기 동작에 잠금을 걸지 않기 위해서 `CopyOnWriteArrayList` 방식으로 write를 한다고 합니다. 이는 리스트를 수정할 때, 배열 전체를 복사하고, 복사한 배열에 수정을 한 뒤, 수정이 완료되면 전체 배열을 갈아끼우는 방식인데, 공식문서를 보니 비용이 많이 드는 작업이라고 나와있습니다. [Oracle-CopyOnWriteArrayList](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CopyOnWriteArrayList.html)
> 
> 저희 서비스 특성상, 전역으로 생성한 ConcurrentCollection를 수정하는 작업이 많이 발생할 것 같습니다. 각 요청(예약,차량 삭제, 에약 가능 날짜 수정)마다 ConcurrentCollection에 데이터를 추가하고, 끝난 뒤에 ConcurrentCollection에서 데이터를 삭제하는 총 2번이 발생하게 되는게 맞겠죠? 게다가 많은 요청이 동시에 들어오게 된다면 ConcurrentCollection의 크기도 커져 CopyOnWriteArrayList하는 비용이 더 커질텐데.. 이런 경우 성능상 이슈가 생길 수 있겠다는 생각이 듭니다. 이 부분에 대해서도 한 번 생각해보면 좋을 것 같아요!

같은 환경에서 애플리케이션 synchronized, DB Lock, 인메모리 DB Lock을 테스트 해보고 결정해보는 건 어떨까요?
