### ISSUE TITLE
[BE] 사용자 인증을 Filter, Interceptor 중 어디에 구현해야 할까요?

### ISSUE THREAD

**Issue by kelly1422** [softeerbootcamp-3rd/Team9-HexaCore#54]
# 사용자 인증을 Filter, Interceptor 중 어디에 구현해야 할까요?

JWT 토큰을 파싱하여 해당 토큰의 무결성을 확인하고 해당 토큰이 만료되었는지 검증하여 로그인한 사용자인지 인증하는 과정을 
Filter에서 구현하는게 좋을지, Interceptor에서 구현하는게 좋을지 고민중에 있습니다.

둘의 차이점을 보자면
Filter는 스프링에 오기 전에 처리할 수 있기 때문에 스프링까지 들어오는 필요를 줄여주고,
Interceptor는 스프링이 기능을 제공하기 때문에 편리하다는 특징이 있습니다.

지금은 Filter에서 구현하고 있습니다.

필터 체인에 아래의 순서로 필터를 등록했습니다.
1. **`ErrorHandlingFilter`** : 이후 필터 체인의 필터들에서 발생한 예외를 공통적으로 받아 클라이언트에 예외 응답을 전송해주는 필터
2. **`JwtAuthenticationFilter`** : 사용자가 전송한 토큰을 이용해 인증하는 필터
3. **`RefreshAccessTokenFilter`** : 리프레시 토큰 요청을 보낸 경우 새로운 엑세스 토큰을 발급해 리턴해주는 필터

Filter로 구현한 이유는 스프링에 오기 전에 처리할 수 있기 때문에 스프링까지 들어오는 오버헤드를 줄일 수 있을거라 생각했기 때문입니다.

하지만 필터에서 발생한 예외를 처리해 공통 응답 형식으로 응답해주기 위해서는 
ErrorHandlingFilter에서 `request.getRequestDispatcher("/api/error").forward(request, response)`를 해주고
/auth/error 등을 처리해줄 컨트롤러도 만들어야 하는 번거로움이 발생한다는 문제가 있었습니다.

## 찾아본 내용

필터는 서블릿 컨테이너에 의해 생성되고, 서블릿 컨테이너 상에 등록됩니다. 
그렇기 때문에 원래 필터는 스프링 빈으로 등록되거나 다른 빈들을 주입받아 사용할 수 없었습니다.

하지만 **`DelegatingFilterProxy`** 의 등장으로 Filter를 스프링 빈으로 등록하고, 다른 빈을 주입받을 수도 있게 되었습니다.
<img width="1067" alt="스크린샷 2024-02-09 오후 7 00 16" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/80809782/e9e97de3-2148-4390-b396-0e368f9b0639">
[출처](https://gowoonsori.com/blog/spring/architecture/)

DelegatingFilterProxy가 작성한 Filter를 스프링 내에 빈으로 등록해 관리하고, 필터가 실행될 때 스프링 빈 컨테이너에서 빈으로 등록되어 있는 Filter를 가져와 실행합니다.

## 결론: Interceptor
JWT를 생성하고 파싱하는 JwtService를 Filter에서 사용하게 된다면, 
필터를 빈으로 등록하고, 스프링의 빈 관리 및 의존성 주입이 일어나는 과정과
각 필터마다 스프링 컨텍스트에서 빈을 가져오는 과정에서 오버헤드가 일어날 수 있다고 판단했습니다.
(Filter는 Servlet API와 직접적으로 상호작용하며, Spring MVC의 컨트롤러와는 별개로 동작하는데, 이로 인해 Filter 내에서 스프링 빈에 직접 접근하는 과정에서 추가적인 오버헤드가 발생할 수 있다고 합니다.)

스프링으로 들어오기 전에 처리가 가능할거라고 생각했지만, 
오히려 스프링 빈으로 등록한 필터를 가져오고, 필터 내에서 사용하는 JwtService 등의 빈을 불러오는 과정에서 오히려 더 큰 오버헤드가 발생하게 되는 것이죠.

또한 서블릿 컨테이너 레벨에서 실행되는 필터에서 JwtService와 같은 스프링의 빈들을 가져다 쓰는 것보다,
스프링 컨테이너에서 실행되는 Interceptor에서 쓰는 것이 더 적절하다고 생각했습니다.

결론적으로 Filter 에서는 
* 보안 관련 공통 작업
* 모든 요청에 대한 로깅 또는 감사

Interceptor 에서는 스프링 기능을 사용해야 하는
- 인증/인가 등과 같은 공통 작업
- Controller로 넘겨주는 정보의 가공

등을 진행하는 것이 적절하다고 생각하고, 현재 구현중인 사용자 인증은 Filter가 아닌 Interceptor에서 구현하려고 합니다.
혹시 다른 의견 있으시면 말씀해주세요!

**Comment by SuHyeon00** [comment]
`JwtAuthenticationFilter`를 스프링의 빈으로 관리하는 이유가 있나요? 들어온 요청의 토큰이 유효한 지 확인하는 작업은 필터에서 해도 되지 않을까요?

**Comment by Yoon-Suji** [comment]
저는 정리해주신 내용을 읽다보니.. Filter에 구현해야 하는게 아닌가..? 싶은 생각이 듭니다!

저희가 하고자하는 건 사용자가 보내는 JWT 토큰이 유효한 지 여부를 확인하고, JWT 토큰을 열어서 저장된 데이터(ex. userId)를 Controller에 보내주는 작업이라고 생각했습니다.(Request 객체에 저장해서 보내줄 수도 있고, 다른 방법을 찾아볼 수도 있겠죠..? Spring Security에서는 Request 객체에 직접 저장하지 않고 SecurityContext에 저장한다고 합니다.) Authentication(인증)과 Authorization(인가) 중에서 **Authentication**에 해당하는 부분이요!

본문에 "Filter에서는 보안 관련 공통 작업, Interceptor에서는 인증/인가 등과 같은 공통 작업" 이라고 적혀 있는데 저는 이걸 Filter에서는 JWT 토큰의 유효성 검증 즉, Authentication과 같은 공통적인 작업을 수행하고 Interceptor에서는 JWT 토큰 내부에 저장된 내용을 가지고 추가적인 인증(Authorization)이 필요할 때 진행하는 작업을 수행한다고 이해했습니다. 예를 들어서 user가 호스트, 게스트로 분리되어 있고 JWT에 userId가 저장되어있다면, Filter에서는 JWT 토큰의 유효성을 검증해서 Request에 userId를 저장해서 전달하고, Interceptor에서는 userId를 바탕으로 호스트만 접근할 수 있는 인증을 구현하는 방식으로요! (물론 정답이 없는 부분이니 모두 Filter에서 구현할 수도 있을 것 같습니다.)

그리고 무엇보다도 Spring Security에서 인증/인가를 구현하는 방식도 Filter(Security Filter Chain)를 사용한다고 합니다. 말씀해주신 것처럼 ExceptionTranslationFilter를 사용해서 예외처리를 따로 진행하고요! 
또한 JWT 토큰의 유효성을 검사하는 건 말 그대로 단순히 서명을 검증하는 작업이기 때문에 데이터를 사용하는 로직이 아니라고 생각합니다. JwtService를 가져와서 사용할 필요도, 저희 데이터베이스에 접근할 필요도 없는 작업인거죠..! 그렇기 때문에 Spring 컨테이너 내부로 가져오기 전에 Filter에서 구현을 하는 게 적절할 것 같습니다.

하지만!! 위에서 논의하셨던 것처럼 ErrorExceptionHandler와 비슷하게 중복되는 코드의 반복 같은 부분은 저도 동의하고 Filter와 Interceptor 모두 가능한 방법이기 때문에 이미 Interceptor로 구현하고 있다면 굳이 리소스를 들여서 바꾸지는 않아도 될 것 같습니다. 다만 Interceptor에서 구현하는 게 정답은 아닐 수 있다.. 개인적으로는 Filter에서 구현하는 게 옳은 것 같다.. 라는 의견을 내어봅니다 ㅎㅎ

**Comment by thecloer** [comment]
말씀하신대로 스프링 시큐리티는 필터 기반으로 동작하네요!! [스프링 가이드 - Spring Security Architecture](https://spring.io/guides/topicals/spring-security-architecture)

"스프링이 auth를 필터에서 구현했으니 필터에서 구현하자!" 라는 결론을 내리고 싶지는 않아서 필터로 auth를 구현할 경우 인터셉터에 비해 어떤 이점이 있는지 생각해 봤어요.

필터는 서블릿 컨테이너 내에서 요청 처리의 가장 앞 부분에서 수행돼요. 따라서 필터로 auth를 구현할 경우 서블릿 앞단에서 보안 처리가 가능하고 서블릿 컨테이너의 모든 요청에 대해 일괄적으로 적용할 수 있어요.
반면 인터셉터는 Spring MVC의 DispatcherServlet이 처리하는 요청에 대해서만 적용돼요. 즉 스프링 MVC 컨트롤러로 들어오는 요청에 대해서만 작동하므로 DispatcherServlet을 거치지 않는 정적 리소스 요청 등에는 적용되지 않아요. 

서블릿 컨테이너의 앞단에서 요청을 블락할 수 있다는 점, 서블릿 컨테이너 수준에서 모든 요청에 일괄적으로 적용할 수 있다는 점에서 필터에서 인증/인가를 하는 것이 좋을 것 같다고 생각이 바뀌었네요. 수지님 감사합니다!

**Comment by kelly1422** [comment]
오호.. 저는 공부하면 할수록 정답은 없다는 생각이 드네요 🧐

#### 1. 정적 자원에 대한 요청을 인터셉터를 거치지 않는가?
`Filter -> Dispatcher Servlet -> Handler Mapping -> Interceptor -> Handler Adapter -> Controller `
전체적으로 이러한 흐름을 가지고 있어요.
그런데 만약 정적 자원에 대한 요청이 `Dispatcher Servlet`을 지나지 않는다면 interceptor로 넘어오지 않는건가 해서 static/a.html 파일을 만들어 한번 테스트를 해보았습니다. 그런데 a.html 파일에 대한 요청을 보내도 Interceptor 가 실행되더라구요.
좀 더 알아보니 스프링은 기본적으로 정적 리소스를 처리할 핸들러인 `ResourceHttpRequestHandler`이 등록되어 있어 정적 자원 요청의 핸들러 매핑시에 `ResourceHttpRequestHandler`가 매핑된다고 합니다. 그래서 사실상 정적 자원 요청도 인터셉터에서 처리해줄 수 있는 것이죠!

또한 CSS 파일, 이미지, JavaScript 와 같은 정적파일들은 대부분의 사용자가 열람할 수 있어야 해서 따로 인증을 요구하지 않는 것이 일반적이라고 합니다. 저희는 게다가 정적 파일을 스프링 서버에서 관리하고 있지 않으니, 이 부분은 상관 없지 않을까 합니다!

#### 2. 처음부터 올바르지 않은 요청 (404 Not Found)의 경우에도 Filter를 거쳐야 할까?
정적 파일 요청도 아니도 동적 자원 요청도 아닌 '/nothing' 경로로 요청이 들어왔다고 가정해봅시다.

Filter에 인증을 구현하게 되면, 모든 요청에 대해 인증을 진행하기 때문에 애초에 처리해 줄 수 없는 요청이어도 인증을 진행하게 됩니다.
(인증된 사용자이던, 아니던 어차피 처리해줄 수 없는 요청인데도 무조건 인증을 한다는 부분이 불필요하게 느껴지는 것 같아요)
<img width="342" alt="스크린샷 2024-02-11 오후 1 37 45" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/80809782/ed93cfa7-73a3-41ab-9c44-f2297c1bc53b">

하지만 인터셉터에 구현하게 되면 매핑된 핸들러 정보를 가져오고, 이때 컨트롤러가 매핑된 것이 아닌 `ResourceHttpRequestHandler` 이 매핑된 경우 인증 인터셉터를 실행시키지 않도록 설정하여 
<img width="374" alt="스크린샷 2024-02-11 오후 1 04 19" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/80809782/860170e4-8577-4c3b-9d9f-ee654fd1e72a">
위와 같은 적절한 에러메세지를 전달할 수 있습니다.


#### 3. 필터에서 JwtService를 가져와 사용한 이유
JwtService에 Jwt와 관련된 기능들을 모두 작성했었습니다.
토큰을 생성하고, 토큰을 검증하고, 토큰에 저장된 값들을 읽어오고, 디비에서 리프레시 토큰을 가져오는 모든 기능을 JwtService에 통합해 작성했습니다..   하지만 이 JwtService를 나눠서 Filter에서 사용해야 하는 `토큰을 검증`, `토큰에 저장된 값들을 읽기`  등의 기능을 `JwtUtil` 과 같은 별도의 클래스로 작성하고 `JwtUtil` 를 빈으로 등록하지 않는다면, Filter를 빈으로 등록할 필요도, Filter에서 다른 빈들의 의존성을 주입받을 필요도 없어지겠군요!
(Jwt와 관련된 모든 기능들을 JwtService에 모두 작성하고 이걸 나눌 생각을 못했네요..)

#### 3. Spring Security는 왜 Filter에서 구현했을까?
(일단 알아보니 스프링 시큐리티는 필터를 빈으로 등록하지 않고 서블릿 컨테이너  다른 빈들의 의존성을 주입받을 수 없다고 해요) 서블릿 컨테이너 단에서 
Spring Security는 인증 뿐 아니라 CSRF 공격 방어, 요청이나 응답이 서버에 도달하기 전에 처리되어야 하는 보안 등 다양한 보안 기능을 가지고 있는 것으로 알고 있습니다. 그렇기에 말씀하신 것처럼 서블릿 컨테이너 수준에서 모든 요청에 일괄적으로 적용할 수 있는 필터에서 구현한게 아닌가 싶습니다!
지금의 프로젝트의 경우에는 오직 인증/인가 기능만 구현하고 있기도 해서 요청을 더 정교하게 처리해줄 수 있는 interceptor가 더 좋지 않을까 라는 생각도 들어요.

#### 4. Interceptor의 더 정교하고 편리한 기능 
- 인터셉터 설정할 수 있는 URL 패턴은 서블릿 URL 패턴과는 다르게 매우 정밀하게 설정할 수 있다.
- 인터셉터는 서블릿 필터보다 편리하고, 더 정교하고 다양한 기능을 지원한다.
- 인터셉터는 스프링 MVC 구조에 특화된 필터 기능을 제공한다고 이해하면 된다. 스프링 MVC를 사용하고, 특별히 필터 를 꼭 사용해야 하는 상황이 아니라면 인터셉터를 사용하는 것이 더 편리하다.
- 등등

이건 김영한님이 말씀하신 인터셉터의 장점들인데, 저도 Filter로 구현했다가 Interceptor로 바꾸니까 인터셉터가 개발하기에는 더 편리한 것 같긴 합니다!
둘 중 어디에서도 구현 가능한 기능이라 정답은 없는 것 같아요!
일단 이미 Intercpetor로 개발해서.. PR 날리고 Filter로 고치면 좋겠다 하는 부분 있으면 말씀해주시면 감사하겠습니다 👍

**Comment by SuHyeon00** [comment]
영경님이 정리해주신 내용 중에서 의문이 생긴 부분이 있어 코멘트 남깁니다!

> #### 2. 처음부터 올바르지 않은 요청 (404 Not Found)의 경우에도 Filter를 거쳐야 할까?
> 정적 파일 요청도 아니도 동적 자원 요청도 아닌 '/nothing' 경로로 요청이 들어왔다고 가정해봅시다.
> 
> Filter에 인증을 구현하게 되면, 모든 요청에 대해 인증을 진행하기 때문에 애초에 처리해 줄 수 없는 요청이어도 인증을 진행하게 됩니다. (인증된 사용자이던, 아니던 어차피 처리해줄 수 없는 요청인데도 무조건 인증을 한다는 부분이 불필요하게 느껴지는 것 같아요) 

저희 서비스는 로그인을 하지 않은 유저이더라도 차량 검색 및 상세페이지 조회와 같은 기능은 사용할 수 있고, 유저의 토큰값을 검증해야 하는 부분은 호스트 페이지 접근이나 마이페이지 접근, 예약하기 등과 같은 특정 기능에 대해서만 필요하다고 생각했습니다.

그래서 만약 Filter에 인증을 구현하게 되면 모든 요청에 대해 인증을 진행하는 것이 아닌 **인증이 필요한 요청에 대해서만** 인증을 진행할 것이라 생각했습니다. 이럴 경우 어차피 처리해줄 수 없는 요청에 대해서는 필터를 거치지 않고 (즉, 따로 인증 절차를 거치지 않고) "No static resource"에 해당하는 에러 메시지를 전달해줄 수 있지 않을까요?

**Comment by kelly1422** [comment]
네 저도 인증이 필요한 요청에 대해서만 인증을 진행하는 것이 맞다고 생각합니다! 

하지만 위에서 말씀 드린 것처럼 요청은
`Filter -> Dispatcher Servlet -> Handler Mapping -> Interceptor -> Handler Adapter -> Controller `
순서로 지나게 되어 있고, 모든 요청은 필터를 지나게 되어 있습니다.
그렇기 때문에 사용자 인증을 필터에 구현하게 되면, 모든 요청에 대해 사용자 인증을 거치는 것이지요.

하지만 인터셉터에 구현하게 되면, 인터셉터의 preHandle 내에서 매핑된 핸들러의 종류를 알 수 있습니다.
이 때, 매핑된 핸들러의 종류가 `ResourceHttpRequestHandler` 라면 정적 파일에 대한 요청, 즉 따로 매핑되는 컨트롤러가 없는 경우입니다.

그렇기 때문에 저는 아래와 같은 코드를 작성하여, 정적 파일 요청인 경우에는 바로 return true; 를 하여사용자 인증을 거치지 않도록 구현하였습니다.
```java
if (handler.getClass().equals(ResourceHttpRequestHandler.class) ||
    (httpMethod.equals(HTTP_GET) && canPass(url)) || httpMethod.equals(HTTP_OPTIONS)) {
         return true;
}
```
이렇게 하면 어차피 처리해줄 수 없는 요청에 대해서는 사용자 인증을 거치지 않게 되는 것이죠!
