### ISSUE TITLE
[BE] 이미지 요청 처리 V2

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#58]
## TODO

- [ ] 이미지 파일의 index와 file의 길이가 같은지에 대한 유효성 검사

## 설명

- 현재 이미지 파일을 index와 file 두개의 배열로 입력받고 있음
- 이 두 배열의 길이가 같은지에 대한 유효성 검사가 이루어지지 않고 있음

**Comment by jomulagy** [comment]
현재 dto의 생성을 생성자를 통해 하고 있기 떄문에 @AllArgsConstructor를 사용하는 대신에 생성자를 구현하여 유효성을 검증 하는 것은 어떨까요?

예시
```
public CarUpdateDto(Integer feePerHour, String address, PositionDto position, String description, List<MultipartFile> imageFiles, List<Integer> imageIndexes) {
        this.feePerHour = feePerHour;
        this.address = address;
        this.position = position;
        this.description = description;
        this.imageFiles = imageFiles;
        this.imageIndexes = imageIndexes;

        // 이미지 파일과 이미지 인덱스의 길이가 같은지 확인
        if (imageFiles.size() != imageIndexes.size()) {
            throw new IllegalArgumentException("The length of imageFiles list must be equal to the length of imageIndexes list");
        }
    }
```

**Comment by jomulagy** [comment]
같은 방식으로 차량 등록시에는 두 배열의 길이가 5로 같은지 확인하면 service단에서 이를 확인하는 로직을 제거해도 괜찮을것 같습니다

**Comment by Yoon-Suji** [comment]
@jomulagy 오 말씀하신 방법은 제가 생각하지 못한 방법이네요..!!

다만 개인적으로 DTO는 Data Transfer Object 의 역할이기 때문에 비즈니스 로직은 넣지 않는 게 좋을 것 같다는 생각이 들어요. 어쨌든 이것도 비즈니스 로직이니까 Service에서 검사하고 에러를 발생시키는 게 디버깅할 때도 편리하지 않을까.. 싶습니다..! DTO에서도 에러를 발생시키고 Service 에서도 에러를 발생시키면 뭔가 각자의 역할을 침범하는 느낌이 들어서요.. 

그런데 어쨌든 둘 다 가능한 방법이니까 다른 분들 의견도 궁금합니다ㅎㅎ

**Comment by jomulagy** [comment]
특정 필드에 대한 검증 로직은 dto의 역할이라고 알고 있습니다. 그러나 위에서 제가 말씀드 방법은 코드가 간결하지 못하고 재사용성도 떨어지기 때문에 커스텀 validator를 만드는 것은 어떨까 제안드립니다.

1. Custom Annotation 작성: 두 리스트의 길이가 같은지 확인하기 위한 커스텀 애노테이션을 작성합니다.
```
import javax.validation.Constraint;
import javax.validation.Payload;
import java.lang.annotation.*;

@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Constraint(validatedBy = ImageListsLengthValidator.class)
public @interface ImageListsLengthMatch {
    String message() default "Lengths of imageFiles and imageIndexes do not match";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
```
2. Validator 작성: 커스텀 애노테이션에 대한 유효성 검사를 수행할 Validator 클래스를 작성합니다.
```
import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

public class ImageListsLengthValidator implements ConstraintValidator<ImageListsLengthMatch, CarUpdateDto> {

    @Override
    public void initialize(ImageListsLengthMatch constraintAnnotation) {
    }

    @Override
    public boolean isValid(CarUpdateDto dto, ConstraintValidatorContext context) {
        if (dto == null) {
            return true; // null 값은 유효한 것으로 처리
        }
        return dto.getImageFiles().size() == dto.getImageIndexes().size();
    }
}
```
3. DTO 클래스에 애노테이션 적용: 커스텀 애노테이션을 DTO 클래스에 적용하여 유효성 검사를 수행합니다.
```
import javax.validation.constraints.NotNull;
import java.util.List;

@ImageListsLengthMatch
public class CarUpdateDto {
    // 필드 및 생성자 생략
}
```

**Comment by Yoon-Suji** [comment]
1. "특정 필드에 대한 검증 로직은 dto의 역할" 이라고 하셨는데 저는 만약 DTO가 검증의 역할을 한다면 그건 String 타입에 Integer가 들어가지 않게 검증하는 것처럼 정말 기본적인 로직을 생각했어요! 그렇게 되면 지금 Image 파일이 5개 이하인 경우에 에러를 발생하는 부분도 DTO에서 해줘야 하는 건가? 싶은 의문이 들어서요. 그래서 저는 조심스레 Service에 (List<MultipartFile> imageFiles, List<Integer> imageIndexes) 을 인자로 받아서 크기가 같은지 확인하는 함수를 하나 만들어서 필요한 부분에 사용하는 방법을 제안드려봅니다..(만 합의가 안되면 제가 양보하겠습니다)

2. 어노테이션과 Validator를 사용해서 코드까지 다 작성해오시다니 굉장하십니다..👍 제가 해당 문법에 익숙하지 않아서 그런데 PostCarDto에서도 해당 코드를 사용하려면 ImageListsLengthValidator 클래스에 메서드를 추가해야 하는 건가요?


결론적으로! 현재는 저희가 무조건 Index 갯수와 Image 갯수가 일치해야 하는 상황이니까 DTO 에서 담당해야 한다는 지훈님 말씀도 이해가 갑니다! 만약 다른 분들 의견이 더 달리지 않으면.. ㅎㅎ 지훈님 의견대로 DTO에서 구현해도 좋을 것 같아요 :) 다만 어노테이션 방식이 뭔가 간단한 로직인데 오히려 코드가 불필요하게 복잡해지는 느낌이 들긴 하네요.. (제가 자바를 잘 못해서 그런걸수도..)

**Comment by jomulagy** [comment]
제가 김영한님 강의 보면서 bean validator라는걸 봤었는데 기본적인 타입 검증 외에도 범위나 다른 검증기능들도 제공하는것으로 배웠습니다. 그래서 dto의 책임이지 않을까 라고 생각했습니다.

**Comment by thecloer** [comment]
`CarUpdateDto`와 해당 dto의 유효성을 검증하는 로직은 항상 같이 사용될 것이라 생각되어 `CarUpdateDto`의 유효성 검증 로직을 추가해도 좋을 것 같아요. 
지훈님이 작성해주신 `2. Validator 작성`의 `isValid()` 를 dto에 넣는 것은 어떨까요? 다만 이 함수는 boolean 값을 반환하고 이후 액션은 컨트롤러나 서비스와 같은 사용처에 맡기는 방법은 어떨까요??

```java
public class CarUpdateDto {
    ...
    public Boolean isValid() {
        return this.imageFiles.size() == this.imageIndexes.size();
    }
}

// controller
...
if (!carUpdateDto.isValid())
    throw new IllegalArgumentException("The length of imageFiles list must be equal to the length of imageIndexes list");
...
```

**Comment by jomulagy** [comment]
좋은 생각인것같습니다 이렇게 만들면 dto가 exception을 던지지 않겠군요

**Comment by SuHyeon00** [comment]
저도 요청 데이터에 대한 검증을 비즈니스 로직에 넣지 않는 게 좋을 것 같습니다.
그리고 제가 알고있기로는 `@Valid` 어노테이션을 사용하여 들어온 요청 데이터를 DTO로 변환하기 전에 값을 검증할 수 있는 것으로 알고 있습니다.
현재 저희가 `ErrorExceptionHandler`를 통해 전역 에러에 대한 처리를 하고 있어서 지훈님이 작성해주신 `Custom Annotation`을 사용하여 해당 DTO 클래스에 어노테이션을 달아 해당 에러를 잡을 수 있을 것 같습니다!

```java
@ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ResponseDto> handleValidationExceptions(MethodArgumentNotValidException e) {
        BindingResult result = e.getBindingResult();
        String message = result.getFieldErrors().get(0).getDefaultMessage();
        return new ResponseEntity<>(ResponseDto.error(ErrorCode.VALIDATION_ERROR, message),
                HttpStatus.BAD_REQUEST);
    }
```

**Comment by kelly1422** [comment]
이렇게 커스텀 어노테이션과 Validator를 사용해 DTO의 유효성을 검사하는 방법이 있었군요!

저는 배열 길이 유효성을 검사하는 방법으로는
1. DTO 클래스에 유효성 검사를 위한 isValid 작성
2. Service에 유효성 검사하는 메소드를 추가

중 하나가 좋을 것 같다고 생각합니다!

배열 길이의 유효성을 검사해야 하는 경우가 PostCarDto, CarUpdateDto 모두 필요한 상황이라
그렇게 되면 두 개의 중복되는 어노테이션과 Validator를 작성하거나, 
PostCarDto와 CarUpdateDto가 공통으로 상속받는 부모 클래스를 생성해야 할 것 같은데 
이는 오히려 코드가 너무 복잡해지고, Java의 리플렉션 특성상 런타임 시에 추가적인 타입 정보들을 불러오는 과정에서 성능저하가 발생할 수도 있겠다는 생각이 듭니다.

(쓰다보니 느낀점 : Dto 이름 규칙 얼른 지어야 할 것 같아요,, )

**Comment by SuHyeon00** [comment]
영경님의 말을 듣고 DTO 변환 시 유효성 검증과 서비스 로직 내 유효성 검증이 각각 어디에 초점을 두고 있는지 찾아보는 과정에서 저희가 검증하고자 하는 "이미지 리스트의 사이즈와 이미지 인덱스 리스트의 사이즈가 일치해야 한다"는 비즈니스 규칙에 대한 검증이라 판단하여 **서비스 로직 내에서 해당 유효성 검증**을 하는 것이 좋을 것 같습니다.

1. DTO 변환 시 유효성 검증
: 주로 입력값의 형식이나 범위를 검증 (ex. 이메일 주소 형식이 올바른지,숫자 필드가 음수가 아닌지 등)

2. 서비스 로직 내에서 유효성 검증
: 사용자 입력값이나 비즈니스 규칙에 따라 서비스 로직 내에서 필요한 경우에 유효성 검증

처음에는 단순히 입력값에 대한 유효성 검증이니 DTO 변환 시 검증해야 하지 않나?라는 생각을 하였는데 두 필드 간의 관계를 검증하는 것이라면 일반적인 입력값의 형식이나 범위를 검증하는 것이 아니기 때문에 서비스 로직 내에서 검증하는 것이 좋을 것 같다고 판단하였습니다.
+) 앞에서 말한 일반적인 입력값의 형식이나 범위를 검증하는 것은 배열의 길이가 5개 이하인지 확인한다거나, 저희가 받고자 하는 형식에 맞는지에 대한 검증을 의미한다고 이해하였습니다.

**Comment by jomulagy** [comment]
그러면 sercive 단에서 처리하는걸로 하겠습니다!
