### ISSUE TITLE
[BE] Car 테이블의 dates 필드 저장 타입

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#79]
## 설명
Car 테이블의 dates 필드 타입을 어떻게 저장 할 지

### 현재 저장 방식
* Car 테이블의 dates 필드를 json 타입으로 저장
* ex. '[[시작날짜, 끝나는 날짜], [시작날짜, 끝나는 날짜]]'
* Reservation 테이블에서 rentDate, returnDate를 datetime 타입으로 저장

### 문제점
* 예약 가능한 날짜를 확인하기 위해서 Car 테이블의 dates 값과 Reservation 테이블의 rentDate, returnDate 값을 비교해야 함 (예약이 발생해도 Car 테이블의 dates 필드를 업데이트하지 않기 때문)
* DB 쿼리 레벨에서 데이터를 처리하기 어려운 문제 발생 -> Application 레벨에서 처리해야 함 -> Repository의 Pageable 객체를 직접 구현해야 함

### 하고 싶은 것
DB 쿼리 레벨에서 데이터를 처리하고 싶다.. 할 수 없을까?

## 대안
<img width="1031" alt="image" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/70956926/8a6b7380-be02-4152-9d4b-281faff9b27b">

* car_dates 에는 startDate와 endDate가 겹치는 record는 있으면 안됨
  * ex. (2024-01-04, 2024-01-05), (2024-01-05, 2024-01-06) -> (2024-01-04, 2024-01-06) 으로 수정해서 넣어줘야 함
* (startDate, endDate)로 SELECT 하는 경우

```sql
# sudo code
SELECT * FROM car JOIN car_dates JOIN reservation
WHERE car_dates.start_date <= startDate AND car_dates.end_date >= endDate
AND (reservation.id == null OR (reservation.rent_date > endDate OR reservation.return_date < startDate))
```

**Comment by thecloer** [comment]
예약은 예약 가능 날짜 범위 중 하나에 완전히 포함되어야 한다는 점을 이용한 아이디어에서 만들어진 구조군요!
누가 생각했는지 좋은 아이디어인 것 같네요!

**Comment by Yoon-Suji** [comment]
## 발생한 문제
1. 예약 테이블은 status 값으로 Terminated, Canceled, Ready, Using을 갖고 있음 (하드 딜리트 X)
2. 예약 가능 날짜 테이블에 업데이트(삭제, 수정)가 발생했을 때, 예약 가능 날짜에 연결되어 있는 예약 테이블을 어떻게 처리해야 할까?


## 해결 방안
1. 현재 DB 형식 유지: Canceld, Terminated 상태의 예약 테이블을 삭제하지 않기 위해서는 예약 가능 날짜도 삭제하면 안되고 소프트 딜리트 형식으로 구현해야 함
-> 소프트 딜리트된 예약 가능 날짜 데이터는 단순히 예약 데이터를 차와 연결하기 위해서 존재할 뿐인 데이터가 된다.

2. 예약을 바로 차량과 연결한다. (차량 : 예약 = 1 : N) 예약과 예약 가능 날짜는 직접적으로 연결하지 않는다.

## 결론
* 차량 : 예약 = 1: N, 차량 : 예약 가능한 날짜 = 1 : N , 예약과 예약 가능 날짜는 직접적으로 연결하지 않음.
